Repository meateam/OSpike, pull requests merged in 2019-01, with the labels that each got.

#51 Combining currently testing cases
  .vscode/launch.json
  package-lock.json
  package.json
  scripts/generate_env.js
  src/app.ts
  src/client/client.validator.ts
  src/config.ts
  src/oauth2/management/management.auth.ts
  src/oauth2/management/management.controller.spec.ts
  src/oauth2/management/management.controller.ts
  src/oauth2/management/management.routes.spec.ts
  src/oauth2/management/management.routes.ts
  src/test.ts
  tsconfig.json
Labels: tests

#52 Deployment configuration
  .gitignore
  README.md
  package-lock.json
  package.json
  scripts/generate_env.js
  src/certs/files/certificate.pem
  src/certs/files/jwks.json
  src/certs/files/privatekey.pem
  src/certs/files/publickey.pem
  src/config.ts
  src/oauth2/management/management.controller.ts
  src/test.ts
Labels: configuration

#53 Before commit handy script
  package.json
  scripts/before_commit.js
  scripts/config.js
Labels: configuration, enhancement

#54 Fix token delay critical bug
  src/app.ts
  src/config.ts
  src/oauth2/oauth2.controller.ts
  src/oauth2/oauth2.utils.ts
Labels: bug

#55 Refactor token expiration issue
  src/accessToken/accessToken.model.ts
  src/oauth2/oauth2.controller.ts
Labels: bug, refactor

#58 Fix lower case issue
  src/oauth2/management/management.controller.ts
Labels: bug, fix

#59 Refactor certificate generation
  package-lock.json
  package.json
  scripts/config.js
  scripts/generate_certs.js
Labels: fix, refactor

#60 fix: Fix token payload wasnt showing clientId.
  src/oauth2/oauth2.controller.ts
  src/oauth2/oauth2.utils.ts
Labels: bug, fix

#61 Fix hostname of jwt issuer
  package.json
  src/config.ts
Labels: bug, fix

#62 Fixing update of case insensitive values
  .vscode/launch.json
  src/oauth2/management/management.controller.ts
  src/oauth2/management/management.routes.spec.ts
  src/test.ts
Labels: bug, fix
