Repository meateam/OSpike, pull requests merged in 2019-08, with the labels that each got.

#75 Multiple hosts duplicate bug fix
  src/oauth2/management/management.controller.ts
Labels: bug, fix

#76 Bugfix for multiple hosts port deletion in default https port
  src/client/client.model.ts
  src/oauth2/management/management.controller.ts
Labels: bug, fix

#77 Adding elastic apm monitor for the server
  README.md
  package-lock.json
  package.json
  scripts/after_commit.js
  scripts/before_commit.js
  scripts/config.js
  scripts/generate_env.js
  src/app.ts
  src/oauth2/management/management.controller.ts
  src/utils/error.handler.mongoose.ts
Labels: feature

#78 Logging support
  README.md
  package-lock.json
  package.json
  scripts/after_commit.js
  scripts/config.js
  scripts/generate_env.js
  src/app.ts
  src/db_config.ts
  src/oauth2/management/management.auth.ts
  src/oauth2/management/management.routes.ts
  src/oauth2/oauth2.controller.ts
  src/server.ts
  src/utils/error.handler.ts
  src/utils/logger.ts
Labels: README.md, feature
